/**
 * JG Investment Plus — review preview + screenshots (v2).
 *
 * The send template (emails/jg-introduction-v2.html) loads its images from
 * the production domain (https://www.jginvst.hu/email/…). Those assets only
 * exist there after merge + production deploy, so a feature-branch review
 * needs its own copy:
 *
 * 1. Writes public/email-preview/jg-introduction-v2.html — REVIEW ONLY, never
 *    sent. Identical to the send template except:
 *      - image URLs are site-relative (/email/…), so they load from whatever
 *        host serves the build (a Vercel preview deployment or localhost);
 *      - {{VIEW_ONLINE_URL}} becomes "#";
 *      - a robots noindex meta is added.
 *    All links (CTA, website, legal) stay on https://www.jginvst.hu.
 *    The send template itself is never modified.
 * 2. With --screenshots, serves public/ over a local HTTP server and captures
 *    review PNGs into docs/email/screenshots/ (also reporting horizontal
 *    overflow, broken images and console errors):
 *      desktop.png          1440 × 900, web fonts (Apple Mail-like)
 *      desktop-fallback.png 1440 × 900, web fonts blocked (Gmail / Outlook-like)
 *      mobile.png           390 × 844 @2x
 *      images-off.png       390 × 844 @2x, all images blocked
 *
 *   NODE_PATH="$(npm root -g)" node emails/scripts/build-preview.mjs --screenshots
 *
 * Behind an HTTPS proxy, add NODE_USE_ENV_PROXY=1 so Node can load Google Fonts.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from "node:fs";
import { createServer } from "node:http";
import { dirname, extname, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const TEMPLATE = join(ROOT, "emails/jg-introduction-v2.html");
export const PREVIEW_ROUTE = "/email-preview/jg-introduction-v2.html";
const PREVIEW = join(ROOT, "public", PREVIEW_ROUTE);
const SHOTS = join(ROOT, "docs/email/screenshots");
const PRODUCTION_ASSETS = "https://www.jginvst.hu/email/";

/** Send template → review preview. Exported so check-email.mjs can verify sync. */
export function toPreview(template) {
  return template
    .replaceAll(PRODUCTION_ASSETS, "/email/")
    .replaceAll("{{VIEW_ONLINE_URL}}", "#")
    .replace(
      '<meta charset="utf-8">',
      '<meta charset="utf-8">\n<meta name="robots" content="noindex, nofollow">',
    )
    .replace(
      "<!--\n  JG Investment Plus",
      "<!--\n  REVIEW PREVIEW — generated by emails/scripts/build-preview.mjs. NOT the send template; do not send this file.\n  JG Investment Plus",
    );
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  mkdirSync(dirname(PREVIEW), { recursive: true });
  writeFileSync(PREVIEW, toPreview(readFileSync(TEMPLATE, "utf8")));
  console.log(`Preview: ${PREVIEW.replace(ROOT + "/", "")}  (route ${PREVIEW_ROUTE})`);

  if (process.argv.includes("--screenshots")) await screenshots();
}

/** Minimal static server for public/ — no project dependency. */
function servePublic() {
  const types = { ".html": "text/html; charset=utf-8", ".png": "image/png", ".jpg": "image/jpeg", ".svg": "image/svg+xml" };
  const base = join(ROOT, "public");
  const server = createServer((req, res) => {
    const path = normalize(decodeURIComponent(new URL(req.url, "http://x").pathname));
    const file = join(base, path);
    if (!file.startsWith(base) || !existsSync(file) || !statSync(file).isFile()) {
      res.writeHead(404).end();
      return;
    }
    res.writeHead(200, { "content-type": types[extname(file)] ?? "application/octet-stream" });
    res.end(readFileSync(file));
  });
  return new Promise((ok) => server.listen(0, "127.0.0.1", () => ok(server)));
}

/**
 * Google Fonts are fetched by Node (which honours the environment's proxy and
 * CA settings, e.g. NODE_USE_ENV_PROXY=1) and handed to the page, so the
 * preview browser never needs its own network or certificate setup.
 */
async function fulfilFromNode(route) {
  try {
    const res = await fetch(route.request().url(), {
      headers: { "user-agent": route.request().headers()["user-agent"] },
    });
    return route.fulfill({
      status: res.status,
      headers: {
        "content-type": res.headers.get("content-type") ?? "application/octet-stream",
        "access-control-allow-origin": "*",
      },
      body: Buffer.from(await res.arrayBuffer()),
    });
  } catch {
    return route.abort();
  }
}

async function screenshots() {
  const { chromium } = createRequire(import.meta.url)("playwright");
  mkdirSync(SHOTS, { recursive: true });
  const server = await servePublic();
  const url = `http://127.0.0.1:${server.address().port}${PREVIEW_ROUTE}`;
  const browser = await chromium.launch();
  const shots = [
    { name: "desktop", width: 1440, height: 900 },
    { name: "desktop-fallback", width: 1440, height: 900, blockFonts: true },
    { name: "mobile", width: 390, height: 844, scale: 2 },
    { name: "images-off", width: 390, height: 844, scale: 2, blockImages: true },
  ];
  let problems = 0;
  try {
    for (const s of shots) {
      const page = await browser.newPage({
        viewport: { width: s.width, height: s.height },
        deviceScaleFactor: s.scale ?? 1,
      });
      const consoleErrors = [];
      page.on("console", (m) => m.type() === "error" && consoleErrors.push(m.text()));
      page.on("pageerror", (e) => consoleErrors.push(e.message));
      await page.route("**/*", (route) => {
        const req = route.request();
        const isFont = /fonts\.(googleapis|gstatic)\.com/.test(req.url());
        if (isFont && s.blockFonts) return route.abort();
        if (s.blockImages && req.resourceType() === "image") return route.abort();
        if (isFont) return fulfilFromNode(route);
        // Only the local server and Google Fonts are reachable from the preview.
        if (!req.url().startsWith("http://127.0.0.1")) return route.abort();
        return route.continue();
      });
      const res = await page.goto(url, { waitUntil: "networkidle" });
      await page.evaluate(() => document.fonts.ready);
      const report = await page.evaluate(() => ({
        overflow: document.documentElement.scrollWidth - document.documentElement.clientWidth,
        images: document.images.length,
        broken: [...document.images]
          .filter((i) => getComputedStyle(i).display !== "none" && i.offsetParent !== null)
          .filter((i) => !i.complete || i.naturalWidth === 0)
          .map((i) => i.getAttribute("src")),
      }));
      // Requests we aborted on purpose (blocked fonts/images) are not page errors.
      const realErrors = consoleErrors.filter((e) => !/net::ERR_FAILED/.test(e) || !(s.blockFonts || s.blockImages));
      await page.screenshot({ path: join(SHOTS, `${s.name}.png`), fullPage: true });
      const brokenCount = s.blockImages ? 0 : report.broken.length;
      problems += (res.status() !== 200) + (report.overflow > 0) + brokenCount + realErrors.length;
      console.log(
        `  ${s.name}.png — HTTP ${res.status()}, overflow ${report.overflow}px, images ${report.images}` +
          (s.blockImages ? " (blocked on purpose)" : `, broken ${report.broken.length}`) +
          `, console errors ${realErrors.length}` +
          (report.broken.length && !s.blockImages ? `\n      broken: ${report.broken.join(", ")}` : "") +
          (realErrors.length ? `\n      errors: ${realErrors.join(" | ")}` : ""),
      );
      await page.close();
    }
  } finally {
    await browser.close();
    server.close();
  }
  if (problems) {
    console.error(`✗ ${problems} preview problem(s)`);
    process.exit(1);
  }
}
