/**
 * JG Investment Plus — local email preview + review screenshots (v2).
 *
 * 1. Writes emails/preview/jg-introduction-v2.preview.html: the send template
 *    with {{ASSET_BASE_URL}} pointed at the local public/ folder, so it opens
 *    straight from disk. The send template itself is never modified.
 * 2. With --screenshots, captures review PNGs into docs/email/screenshots/:
 *      desktop.png          1440 px viewport, web fonts (Apple Mail-like)
 *      desktop-fallback.png 1440 px, web fonts blocked (Gmail / Outlook-like:
 *                           Georgia + Arial)
 *      mobile.png           390 px viewport
 *      images-off.png       390 px, all images blocked
 *
 *   NODE_PATH="$(npm root -g)" node emails/scripts/build-preview.mjs --screenshots
 *
 * Behind an HTTPS proxy, add NODE_USE_ENV_PROXY=1 so Node can load Google Fonts.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const TEMPLATE = join(ROOT, "emails/jg-introduction-v2.html");
const PREVIEW = join(ROOT, "emails/preview/jg-introduction-v2.preview.html");
const SHOTS = join(ROOT, "docs/email/screenshots");

const html = readFileSync(TEMPLATE, "utf8")
  .replaceAll("{{ASSET_BASE_URL}}", "../../public")
  .replaceAll("{{VIEW_ONLINE_URL}}", "#");

mkdirSync(dirname(PREVIEW), { recursive: true });
writeFileSync(
  PREVIEW,
  html.replace(
    "<!--\n  JG Investment Plus",
    "<!--\n  LOCAL PREVIEW — generated by emails/scripts/build-preview.mjs. Do not send this file.\n  JG Investment Plus",
  ),
);
console.log(`Preview: ${PREVIEW.replace(ROOT + "/", "")}`);

/**
 * Google Fonts are fetched by Node (which honours the environment's proxy and
 * CA settings, e.g. NODE_USE_ENV_PROXY=1) and handed to the page, so the
 * preview browser never needs its own network or certificate setup.
 */
async function fulfilFromNode(route) {
  try {
    const res = await fetch(route.request().url(), {
      headers: { "user-agent": route.request().headers()["user-agent"] },
    });
    return route.fulfill({
      status: res.status,
      headers: {
        "content-type": res.headers.get("content-type") ?? "application/octet-stream",
        "access-control-allow-origin": "*",
      },
      body: Buffer.from(await res.arrayBuffer()),
    });
  } catch {
    return route.abort();
  }
}

if (process.argv.includes("--screenshots")) {
  const { chromium } = createRequire(import.meta.url)("playwright");
  mkdirSync(SHOTS, { recursive: true });
  const url = pathToFileURL(PREVIEW).href;
  const browser = await chromium.launch();
  const shots = [
    { name: "desktop", width: 1440 },
    { name: "desktop-fallback", width: 1440, blockFonts: true },
    { name: "mobile", width: 390, scale: 2 },
    { name: "images-off", width: 390, scale: 2, blockImages: true },
  ];
  try {
    for (const s of shots) {
      const page = await browser.newPage({
        viewport: { width: s.width, height: 900 },
        deviceScaleFactor: s.scale ?? 1,
      });
      await page.route("**/*", (route) => {
        const req = route.request();
        const isFont = /fonts\.(googleapis|gstatic)\.com/.test(req.url());
        if (isFont && s.blockFonts) return route.abort();
        if (s.blockImages && req.resourceType() === "image") return route.abort();
        if (isFont) return fulfilFromNode(route);
        return route.continue();
      });
      await page.goto(url, { waitUntil: "networkidle" });
      await page.evaluate(() => document.fonts.ready);
      const overflow = await page.evaluate(
        () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
      );
      await page.screenshot({ path: join(SHOTS, `${s.name}.png`), fullPage: true });
      console.log(`  ${s.name}.png — horizontal overflow: ${overflow}px`);
      await page.close();
    }
  } finally {
    await browser.close();
  }
}
